### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by rkakrik** [bitly/asyncmongo#51]
File "/home/krik/LBE3/lib/python3.2/site-packages/asyncmongo/connection.py", line 82
        except socket.error, error:
                           ^
    SyntaxError: invalid syntax

```
  File "/home/krik/LBE3/lib/python3.2/site-packages/asyncmongo/cursor.py", line 47
    return u'%s.%s' % (self.__dbname, self.__collection)
                  ^
SyntaxError: invalid syntax

  File "/home/krik/LBE3/lib/python3.2/site-packages/asyncmongo/errors.py", line 44
    return u'IntegrityError: %s code:%s' % (self.msg, self.code or '')
                                       ^
SyntaxError: invalid syntax
```

**Comment by shiny** [comment]
`import asyncmongo`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/site-packages/asyncmongo/__init__.py", line 37, in <module>
    from errors import (Error, InterfaceError, AuthenticationError, DatabaseError, RSConnectionError,
ImportError: No module named 'errors'
```
